from typing import Final

# Some constants
# CODATA_BASE_URL: Final = ulibp.urlsplit("https://physics.nist.gov")
CODATA_BASE_URL: Final[str] = "https://physics.nist.gov"
CODATA_CATEGORY_BASE_URL: Final[str] = (
    f"{CODATA_BASE_URL}/cgi-bin/cuu/Category?view=html"
)
CODATA_CONSTANT_LATEX_IMAGE_BASE_URL = f"{CODATA_BASE_URL}/cuu/Constants/Value/gif/"

AUTOGENERATED_TEXT: Final[str] = (
    "This file was autogenerated. Please refer to the project README for instructions."
)
