import pathlib
import textwrap
from typing import Final, overload

import tex2typst
import yaml

from .config_constants import AUTOGENERATED_TEXT_CODATA2022
from .helpclasses import Constant, ConstantCategory

# Hardcoded symbols of constants where automatic conversion fails
_EXTRA_SYMBOL_HANDLING: Final[dict[str, str]] = {
    "molar mass of carbon-12": "$M(attach(upright(C), tl: 12))$",
}


def constants2yaml(constants: list[Constant], ofolder: pathlib.Path) -> None:
    """Write the list of constants to a yaml file."""
    file_header = textwrap.indent(AUTOGENERATED_TEXT_CODATA2022, "# ")
    with open(ofolder / "constants.yaml", "w", encoding="utf-8") as ofile:
        _ = ofile.write(file_header)
        yaml.dump(
            [constant.to_yaml_dict() for constant in constants],
            ofile,
            sort_keys=False,
        )


def constants2typst(
    categorized_constants: dict[ConstantCategory | None, list[Constant]],
    ofolder: pathlib.Path,
    filename_uncategorized_groups: str = "uncategorized",
) -> pathlib.Path:
    """Write the list of constants to a Typst files.

    Each Typst file represents one of the categories.

    Parameters
    ----------
    categorized_constants
        The constants categorized into the `ConstantCategory`s. All that cannot be grouped into one
        of the categories should be added to the dict entry `None`.
    ofolder
        The folder into which the Typst files should be saved.
    filename_uncategorized_groups
        The filename for the constants that do not belong into a category and are in the `None` key.

    Returns
    -------
        The path and filename of the Typst import file for the datasets categories.
    """

    @overload
    def convert_none(val: None | str) -> str:
        pass

    @overload
    def convert_none(val: float) -> int | float:
        pass

    def convert_none(val: None | str | float) -> str | int | float:
        """Convert values that might be python `None` to Typst none."""
        if val is None:
            return "none"
        return val

    typst_file_header = (
        textwrap.indent(AUTOGENERATED_TEXT_CODATA2022, r"\\ ")
        + '#import "../common_packages.typ": *\n\n'
    )

    def convert_unitstr2typstcontent(string: str | None) -> str:
        """Convert a unit string to a Typst valid content string."""
        if string is None:
            return convert_none(string)

        # Apply some initial string replacing
        string_pp = (
            string.replace("$", "")
            .replace(r"\it", r"\mathit")  # Old and deprecated LaTeX font command
            .replace(r"\rmmu", r"\rm \mu")  # Not really sure, maybe typo on website
            .replace(r"\rmssmu", r"\rm \mu")  # Not really sure, maybe typo on website
            .replace(r"\rmpi", r"\rm \pi")  # Not really sure, maybe typo on website
            .replace(r"\rmtau", r"\rm \tau")  # Not really sure, maybe typo on website
            .replace(r"\rmsstau", r"\rm \tau")  # Not really sure, maybe typo on website
            .replace(r"\lbar", r"ƛ")
            .replace(r"\lambdabar", r"ƛ")
        )

        tex2typst_output = tex2typst.tex2typst(string_pp)

        return f"${tex2typst_output.rstrip('\n')}$"

    dataset_import_file_name = ofolder / f"{ofolder.stem.lower()}.typ"
    with open(dataset_import_file_name, mode="w", encoding="utf-8") as import_file:
        for category, category_constants in categorized_constants.items():
            if len(category_constants) > 0:
                category_filename = f"{filename_uncategorized_groups if category is None else category.name.lower()}.typ"
                with open(
                    ofolder / category_filename, mode="w", encoding="utf-8"
                ) as of:
                    _ = of.write(typst_file_header)
                    for const in category_constants:
                        _ = of.write(
                            textwrap.dedent(
                                f"""\
                                #let {const.typst_variable_name} = (
                                  val: {const.value},
                                  uncert: {convert_none(const.uncertainty)},
                                  unit: "{convert_none(const.unit)}",
                                  symbol: {_EXTRA_SYMBOL_HANDLING[const.quantity] if const.quantity in _EXTRA_SYMBOL_HANDLING else convert_unitstr2typstcontent(const.symbol)},
                                  quantity: "{const.quantity}"
                                )
                                """
                            )
                        )

                _ = import_file.write(f"""#import "{category_filename}"\n""")

    return dataset_import_file_name


def write_unittest_files(
    categorized_constants: dict[ConstantCategory | None, list[Constant]],
    dataset_import_filename: pathlib.Path,
    unittestfolder: pathlib.Path,
    filename_uncategorized_groups: str = "uncategorized",
) -> None:
    """_summary_

    Parameters
    ----------
    categorized_constants
        _description_
    dataset_import_filename
        The file where the categorized constant imports are written to.
    """
    with open(unittestfolder / "test.typ", mode="w", encoding="utf-8") as test_file:
        import_path = dataset_import_filename.absolute().relative_to(
            unittestfolder.absolute(), walk_up=True
        )
        _ = test_file.write(
            textwrap.dedent(
                f"""\
                #import "@preview/unify:0.8.1"
                #import "@preview/zero:0.6.1"

                #import "{import_path}"

                #show link: underline


                #title([#upper("{dataset_import_filename.stem}") Test File])

                #outline(title: "Constant categories")\n
                """
            )
        )

        for category, constants in categorized_constants.items():
            _ = test_file.write(f"= {category}\n\n")
            _ = test_file.write(
                textwrap.dedent(
                    """\
                    #table(
                      columns: 5,
                      // inset: 10pt,
                      // align: horizon,
                      table.header(
                        [*Quantity*], [*Symbol*], [*Value*], [*Uncertainty*], [*Unit (#link("https://typst.app/universe/package/unify/")[unify])*]
                      ),
                    """
                )
            )

            for constant in constants:
                const_qualifier = f"{import_path.stem}.{filename_uncategorized_groups if category is None else category.name.lower()}.{constant.typst_variable_name}"

                uncert_str = (
                    '"(exact)"'
                    if constant.uncertainty is None
                    else str(f'zero.num({const_qualifier}.uncert, exponent: "sci")')
                )
                _ = test_file.write(
                    f"  {const_qualifier}.quantity,\n"
                    + f"  [#{const_qualifier}.symbol],\n"
                    + f'  zero.num({const_qualifier}.val, exponent: "sci"),\n'
                    + f"  {uncert_str},\n"
                    + f"  unify.unit({const_qualifier}.unit),\n\n"
                )

            _ = test_file.write(")\n\n")
