import pathlib
import textwrap

import yaml

from .config_constants import AUTOGENERATED_TEXT
from .helpclasses import Constant, ConstantCategory


def constants2yaml(constants: list[Constant], ofolder: pathlib.Path) -> None:
    """Write the list of constants to a yaml file."""
    file_header = f"# {AUTOGENERATED_TEXT}\n"
    with open(ofolder / "constants.yaml", "w", encoding="utf-8") as ofile:
        _ = ofile.write(file_header)
        yaml.dump(
            [constant.to_yaml_dict() for constant in constants],
            ofile,
            sort_keys=False,
        )


def constants2typst(
    constants: list[Constant],
    ofolder: pathlib.Path,
    filename_uncategorized_groups: str = "uncategorized",
) -> None:
    """Write the list of constants to a typst file."""

    def convert_none(val: None | str | float) -> str | int | float:
        """Convert values that might be python `None` to typst none."""
        if val is None:
            return "none"
        return val

    typst_file_header = textwrap.dedent(
        f"""\
        // {AUTOGENERATED_TEXT}

        #import "../common_packages.typ": *

        """
    )

    category_groups: dict[ConstantCategory | None, list[Constant]] = {
        cc: [] for cc in list(ConstantCategory) + [None]
    }
    for constant in constants:
        if len(constant.categories) == 0:
            category_groups[None].append(constant)
            continue
        for category in constant.categories:
            category_groups[category].append(constant)

    dataset_import_file_name = ofolder / f"{ofolder.stem.lower()}.typ"
    with open(dataset_import_file_name, "w", encoding="utf-8") as import_file:
        for category, category_constants in category_groups.items():
            if len(category_constants) > 0:
                category_filename = f"{filename_uncategorized_groups if category is None else category.name.lower()}.typ"
                with open(ofolder / category_filename, "w", encoding="utf-8") as of:
                    _ = of.write(typst_file_header)
                    for const in category_constants:
                        _ = of.write(
                            f"""#let {const.typst_variable_name} = (val: {const.value}, uncert: {convert_none(const.uncertainty)}, unit: "{convert_none(const.unit)}", symbol: "{const.symbol}", quantity: "{const.quantity}")\n"""
                        )

                _ = import_file.write(f"""#import "{category_filename}"\n""")
