// This file was autogenerated. Please refer to the project README for instructions.

#import "../common_packages.typ": *

#let avogadro_constant = (
  val: 6.02214076e+23,
  uncert: none,
  unit: "mol^-1",
  symbol: $N_upright(A)$,
  quantity: "Avogadro constant"
)
#let boltzmann_constant = (
  val: 1.380649e-23,
  uncert: none,
  unit: "J K^-1",
  symbol: $k$,
  quantity: "Boltzmann constant"
)
#let elementary_charge = (
  val: 1.602176634e-19,
  uncert: none,
  unit: "C",
  symbol: $e$,
  quantity: "elementary charge"
)
#let hyperfine_transition_frequency_of_cs-133 = (
  val: 9192631770,
  uncert: none,
  unit: "Hz",
  symbol: $Delta nu_(upright(C) s)$,
  quantity: "hyperfine transition frequency of Cs-133"
)
#let luminous_efficacy = (
  val: 683,
  uncert: none,
  unit: "lm W^-1",
  symbol: $K_(upright(c) d)$,
  quantity: "luminous efficacy"
)
#let planck_constant = (
  val: 6.62607015e-34,
  uncert: none,
  unit: "J Hz^-1",
  symbol: $h$,
  quantity: "Planck constant"
)
#let reduced_planck_constant = (
  val: 1.054571817e-34,
  uncert: none,
  unit: "J s",
  symbol: $planck$,
  quantity: "reduced Planck constant"
)
#let speed_of_light_in_vacuum = (
  val: 299792458,
  uncert: none,
  unit: "m s^-1",
  symbol: $c$,
  quantity: "speed of light in vacuum"
)
#let standard_acceleration_of_gravity = (
  val: 9.80665,
  uncert: none,
  unit: "m s^-2",
  symbol: $g_upright(n)$,
  quantity: "standard acceleration of gravity"
)
#let standard_atmosphere = (
  val: 101325,
  uncert: none,
  unit: "Pa",
  symbol: $a t m$,
  quantity: "standard atmosphere"
)
#let standard-state_pressure = (
  val: 100000,
  uncert: none,
  unit: "Pa",
  symbol: $s s p$,
  quantity: "standard-state pressure"
)
