\\ This file was autogenerated. Please refer to the project README for instructions.

\\ The data contained in this file were retrieved from the NIST CODATA 2022 database.

\\ Eite Tiesinga, Peter J. Mohr, David B. Newell, and Barry N. Taylor (2024), "The 2022 CODATA
\\ Recommended Values of the Fundamental Physical Constants" (Web Version 9.0). Database developed
\\ by J. Baker, M. Douma, and S. Kotochigova. Available at https://physics.nist.gov/constants,
\\ National Institute of Standards and Technology, Gaithersburg, MD 20899.


#import "../common_packages.typ": *

#let alphaParticleRelativeAtomicMass = (
  val: 4.001506179129,
  uncert: 6.2e-11,
  unit: "none",
  symbol: none,
  quantity: "alpha particle relative atomic mass"
)
#let atomicUnitOfElectricDipoleMom = (
  val: 8.4783536198e-30,
  uncert: 1.3e-39,
  unit: "C m",
  symbol: none,
  quantity: "atomic unit of electric dipole mom."
)
#let atomicUnitOfElectricQuadrupoleMom = (
  val: 4.4865515185e-40,
  uncert: 1.4e-49,
  unit: "C m^2",
  symbol: none,
  quantity: "atomic unit of electric quadrupole mom."
)
#let atomicUnitOfMagDipoleMom = (
  val: 1.85480201315e-23,
  uncert: 5.8e-33,
  unit: "J T^-1",
  symbol: none,
  quantity: "atomic unit of mag. dipole mom."
)
#let atomicUnitOfMagFluxDensity = (
  val: 235051.757077,
  uncert: 7.3e-05,
  unit: "T",
  symbol: none,
  quantity: "atomic unit of mag. flux density"
)
#let deuteronelectronMagMomRatio = (
  val: -0.000466434555,
  uncert: 1.2e-12,
  unit: "none",
  symbol: none,
  quantity: "deuteron-electron mag. mom. ratio"
)
#let deuteronMagMom = (
  val: 4.330735087e-27,
  uncert: 1.1e-35,
  unit: " J T^-1",
  symbol: none,
  quantity: "deuteron mag. mom."
)
#let deuteronMagMomToBohrMagnetonRatio = (
  val: 0.0004669754568,
  uncert: 1.2e-12,
  unit: "none",
  symbol: none,
  quantity: "deuteron mag. mom. to Bohr magneton ratio"
)
#let deuteronMagMomToNuclearMagnetonRatio = (
  val: 0.8574382335,
  uncert: 2.2e-09,
  unit: "none",
  symbol: none,
  quantity: "deuteron mag. mom. to nuclear magneton ratio"
)
#let deuteronneutronMagMomRatio = (
  val: -0.44820652,
  uncert: 1.1e-07,
  unit: "none",
  symbol: none,
  quantity: "deuteron-neutron mag. mom. ratio"
)
#let deuteronprotonMagMomRatio = (
  val: 0.3070122093,
  uncert: 7.9e-10,
  unit: "none",
  symbol: none,
  quantity: "deuteron-proton mag. mom. ratio"
)
#let deuteronRelativeAtomicMass = (
  val: 2.013553212544,
  uncert: 1.5e-11,
  unit: "none",
  symbol: none,
  quantity: "deuteron relative atomic mass"
)
#let electrondeuteronMagMomRatio = (
  val: -2143.9234921,
  uncert: 5.6e-06,
  unit: "none",
  symbol: none,
  quantity: "electron-deuteron mag. mom. ratio"
)
#let electronGyromagRatio = (
  val: 176085962784.0,
  uncert: 55.0,
  unit: " s^-1 T^-1",
  symbol: none,
  quantity: "electron gyromag. ratio"
)
#let electronGyromagRatioInMhzPerT = (
  val: 28024.9513861,
  uncert: 8.7e-06,
  unit: " MHz T^-1",
  symbol: none,
  quantity: "electron gyromag. ratio in MHz/T"
)
#let electronMagMom = (
  val: -9.2847646917e-24,
  uncert: 2.9e-33,
  unit: "J T^-1",
  symbol: none,
  quantity: "electron mag. mom."
)
#let electronMagMomAnomaly = (
  val: 0.00115965218046,
  uncert: 1.8e-13,
  unit: "none",
  symbol: none,
  quantity: "electron mag. mom. anomaly"
)
#let electronMagMomToBohrMagnetonRatio = (
  val: -1.00115965218046,
  uncert: 1.8e-13,
  unit: "none",
  symbol: none,
  quantity: "electron mag. mom. to Bohr magneton ratio"
)
#let electronMagMomToNuclearMagnetonRatio = (
  val: -1838.281971877,
  uncert: 3.2e-08,
  unit: "none",
  symbol: none,
  quantity: "electron mag. mom. to nuclear magneton ratio"
)
#let electronmuonMagMomRatio = (
  val: 206.7669881,
  uncert: 4.6e-06,
  unit: "none",
  symbol: none,
  quantity: "electron-muon mag. mom. ratio"
)
#let electronneutronMagMomRatio = (
  val: 960.92048,
  uncert: 0.00023,
  unit: "none",
  symbol: none,
  quantity: "electron-neutron mag. mom. ratio"
)
#let electronprotonMagMomRatio = (
  val: -658.21068789,
  uncert: 1.9e-07,
  unit: "none",
  symbol: none,
  quantity: "electron-proton mag. mom. ratio"
)
#let electronRelativeAtomicMass = (
  val: 0.0005485799090441,
  uncert: 9.7e-15,
  unit: "none",
  symbol: none,
  quantity: "electron relative atomic mass"
)
#let electronToShieldedHelionMagMomRatio = (
  val: 864.05823986,
  uncert: 7e-07,
  unit: "none",
  symbol: none,
  quantity: "electron to shielded helion mag. mom. ratio"
)
#let electronToShieldedProtonMagMomRatio = (
  val: -658.2275856,
  uncert: 2.7e-06,
  unit: "none",
  symbol: none,
  quantity: "electron to shielded proton mag. mom. ratio"
)
#let electronVolt = (
  val: 1.602176634e-19,
  uncert: none,
  unit: "J",
  symbol: none,
  quantity: "electron volt"
)
#let helionMagMom = (
  val: -1.07461755198e-26,
  uncert: 9.3e-36,
  unit: "J T^-1",
  symbol: none,
  quantity: "helion mag. mom."
)
#let helionMagMomToBohrMagnetonRatio = (
  val: -0.00115874098083,
  uncert: 9.4e-13,
  unit: "none",
  symbol: none,
  quantity: "helion mag. mom. to Bohr magneton ratio"
)
#let helionMagMomToNuclearMagnetonRatio = (
  val: -2.1276253498,
  uncert: 1.7e-09,
  unit: "none",
  symbol: none,
  quantity: "helion mag. mom. to nuclear magneton ratio"
)
#let helionRelativeAtomicMass = (
  val: 3.014932246932,
  uncert: 7.4e-11,
  unit: "none",
  symbol: none,
  quantity: "helion relative atomic mass"
)
#let helionShieldingShift = (
  val: 5.9967029e-05,
  uncert: 2.3e-11,
  unit: "none",
  symbol: none,
  quantity: "helion shielding shift"
)
#let magFluxQuantum = (
  val: 2.067833848e-15,
  uncert: none,
  unit: "Wb",
  symbol: none,
  quantity: "mag. flux quantum"
)
#let muonMagMom = (
  val: -4.4904483e-26,
  uncert: 1e-33,
  unit: "J T^-1",
  symbol: none,
  quantity: "muon mag. mom."
)
#let muonMagMomAnomaly = (
  val: 0.00116592062,
  uncert: 4.1e-10,
  unit: "none",
  symbol: none,
  quantity: "muon mag. mom. anomaly"
)
#let muonMagMomToBohrMagnetonRatio = (
  val: -0.00484197048,
  uncert: 1.1e-10,
  unit: "none",
  symbol: none,
  quantity: "muon mag. mom. to Bohr magneton ratio"
)
#let muonMagMomToNuclearMagnetonRatio = (
  val: -8.89059704,
  uncert: 2e-07,
  unit: "none",
  symbol: none,
  quantity: "muon mag. mom. to nuclear magneton ratio"
)
#let muonprotonMagMomRatio = (
  val: -3.183345146,
  uncert: 7.1e-08,
  unit: "none",
  symbol: none,
  quantity: "muon-proton mag. mom. ratio"
)
#let neutronelectronMagMomRatio = (
  val: 0.00104066884,
  uncert: 2.4e-10,
  unit: "none",
  symbol: none,
  quantity: "neutron-electron mag. mom. ratio"
)
#let neutronGyromagRatio = (
  val: 183247174.0,
  uncert: 43.0,
  unit: "s^-1 T^-1",
  symbol: none,
  quantity: "neutron gyromag. ratio"
)
#let neutronGyromagRatioInMhzPerT = (
  val: 29.1646935,
  uncert: 6.9e-06,
  unit: " MHz T^-1",
  symbol: none,
  quantity: "neutron gyromag. ratio in MHz/T"
)
#let neutronMagMom = (
  val: -9.6623653e-27,
  uncert: 2.3e-33,
  unit: "J T^-1",
  symbol: none,
  quantity: "neutron mag. mom."
)
#let neutronMagMomToBohrMagnetonRatio = (
  val: -0.00104187565,
  uncert: 2.5e-10,
  unit: "none",
  symbol: none,
  quantity: "neutron mag. mom. to Bohr magneton ratio"
)
#let neutronMagMomToNuclearMagnetonRatio = (
  val: -1.91304276,
  uncert: 4.5e-07,
  unit: "none",
  symbol: none,
  quantity: "neutron mag. mom. to nuclear magneton ratio"
)
#let neutronprotonMagMomRatio = (
  val: -0.68497935,
  uncert: 1.6e-07,
  unit: "none",
  symbol: none,
  quantity: "neutron-proton mag. mom. ratio"
)
#let neutronRelativeAtomicMass = (
  val: 1.00866491606,
  uncert: 4e-10,
  unit: "none",
  symbol: none,
  quantity: "neutron relative atomic mass"
)
#let neutronToShieldedProtonMagMomRatio = (
  val: -0.68499694,
  uncert: 1.6e-07,
  unit: "none",
  symbol: none,
  quantity: "neutron to shielded proton mag. mom. ratio"
)
#let protonGyromagRatio = (
  val: 267522187.08,
  uncert: 0.11,
  unit: "s^-1 T^-1",
  symbol: none,
  quantity: "proton gyromag. ratio"
)
#let protonGyromagRatioInMhzPerT = (
  val: 42.577478461,
  uncert: 1.8e-08,
  unit: "MHz T^-1",
  symbol: none,
  quantity: "proton gyromag. ratio in MHz/T"
)
#let protonMagMom = (
  val: 1.41060679545e-26,
  uncert: 6e-36,
  unit: "J T^-1",
  symbol: none,
  quantity: "proton mag. mom."
)
#let protonMagMomToBohrMagnetonRatio = (
  val: 0.0015210322023,
  uncert: 4.5e-13,
  unit: "none",
  symbol: none,
  quantity: "proton mag. mom. to Bohr magneton ratio"
)
#let protonMagMomToNuclearMagnetonRatio = (
  val: 2.79284734463,
  uncert: 8.2e-10,
  unit: "none",
  symbol: none,
  quantity: "proton mag. mom. to nuclear magneton ratio"
)
#let protonMagShieldingCorrection = (
  val: 2.56715e-05,
  uncert: 4.1e-09,
  unit: "none",
  symbol: none,
  quantity: "proton mag. shielding correction"
)
#let protonneutronMagMomRatio = (
  val: -1.45989802,
  uncert: 3.4e-07,
  unit: "none",
  symbol: none,
  quantity: "proton-neutron mag. mom. ratio"
)
#let protonRelativeAtomicMass = (
  val: 1.0072764665789,
  uncert: 8.3e-12,
  unit: "none",
  symbol: none,
  quantity: "proton relative atomic mass"
)
#let shieldedHelionGyromagRatio = (
  val: 203789460.78,
  uncert: 0.18,
  unit: "s^-1 T^-1",
  symbol: none,
  quantity: "shielded helion gyromag. ratio"
)
#let shieldedHelionGyromagRatioInMhzPerT = (
  val: 32.434100033,
  uncert: 2.8e-08,
  unit: "MHz T^-1",
  symbol: none,
  quantity: "shielded helion gyromag. ratio in MHz/T"
)
#let shieldedHelionMagMom = (
  val: -1.07455311035e-26,
  uncert: 9.3e-36,
  unit: "J T^-1",
  symbol: none,
  quantity: "shielded helion mag. mom."
)
#let shieldedHelionMagMomToBohrMagnetonRatio = (
  val: -0.00115867149457,
  uncert: 9.4e-13,
  unit: "none",
  symbol: none,
  quantity: "shielded helion mag. mom. to Bohr magneton ratio"
)
#let shieldedHelionMagMomToNuclearMagnetonRatio = (
  val: -2.1274977624,
  uncert: 1.7e-09,
  unit: "none",
  symbol: none,
  quantity: "shielded helion mag. mom. to nuclear magneton ratio"
)
#let shieldedHelionToProtonMagMomRatio = (
  val: -0.76176657721,
  uncert: 6.6e-10,
  unit: "none",
  symbol: none,
  quantity: "shielded helion to proton mag. mom. ratio"
)
#let shieldedHelionToShieldedProtonMagMomRatio = (
  val: -0.7617861334,
  uncert: 3.1e-09,
  unit: "none",
  symbol: none,
  quantity: "shielded helion to shielded proton mag. mom. ratio"
)
#let shieldedProtonGyromagRatio = (
  val: 267515319.4,
  uncert: 1.1,
  unit: " s^-1 T^-1",
  symbol: none,
  quantity: "shielded proton gyromag. ratio"
)
#let shieldedProtonGyromagRatioInMhzPerT = (
  val: 42.57638543,
  uncert: 1.7e-07,
  unit: " MHz T^-1",
  symbol: none,
  quantity: "shielded proton gyromag. ratio in MHz/T"
)
#let shieldedProtonMagMom = (
  val: 1.410570583e-26,
  uncert: 5.8e-35,
  unit: "J T^-1",
  symbol: none,
  quantity: "shielded proton mag. mom."
)
#let shieldedProtonMagMomToBohrMagnetonRatio = (
  val: 0.0015209931551,
  uncert: 6.2e-12,
  unit: "none",
  symbol: none,
  quantity: "shielded proton mag. mom. to Bohr magneton ratio"
)
#let shieldedProtonMagMomToNuclearMagnetonRatio = (
  val: 2.792775648,
  uncert: 1.1e-08,
  unit: "none",
  symbol: none,
  quantity: "shielded proton mag. mom. to nuclear magneton ratio"
)
#let shieldingDifferenceOfDAndPInHd = (
  val: 1.9877e-08,
  uncert: 1e-12,
  unit: "none",
  symbol: none,
  quantity: "shielding difference of d and p in HD"
)
#let shieldingDifferenceOfTAndPInHt = (
  val: 2.3945e-08,
  uncert: 2e-12,
  unit: "none",
  symbol: none,
  quantity: "shielding difference of t and p in HT"
)
#let tritonMagMom = (
  val: 1.5046095178e-26,
  uncert: 3e-35,
  unit: "J T^-1",
  symbol: none,
  quantity: "triton mag. mom."
)
#let tritonMagMomToBohrMagnetonRatio = (
  val: 0.0016223936648,
  uncert: 3.2e-12,
  unit: "none",
  symbol: none,
  quantity: "triton mag. mom. to Bohr magneton ratio"
)
#let tritonMagMomToNuclearMagnetonRatio = (
  val: 2.978962465,
  uncert: 5.9e-09,
  unit: "none",
  symbol: none,
  quantity: "triton mag. mom. to nuclear magneton ratio"
)
#let tritonRelativeAtomicMass = (
  val: 3.01550071597,
  uncert: 1e-10,
  unit: "none",
  symbol: none,
  quantity: "triton relative atomic mass"
)
#let tritonToProtonMagMomRatio = (
  val: 1.0666399189,
  uncert: 2.1e-09,
  unit: "none",
  symbol: none,
  quantity: "triton to proton mag. mom. ratio"
)
#let unifiedAtomicMassUnit = (
  val: 1.66053906892e-27,
  uncert: 5.2e-37,
  unit: "kg",
  symbol: none,
  quantity: "unified atomic mass unit"
)
#let vacuumMagPermeability = (
  val: 1.25663706127e-06,
  uncert: 2e-16,
  unit: " N A^-2",
  symbol: none,
  quantity: "vacuum mag. permeability"
)
#let wToZMassRatio = (
  val: 0.88145,
  uncert: 0.00013,
  unit: "none",
  symbol: none,
  quantity: "W to Z mass ratio"
)
