\\ This file was autogenerated. Please refer to the project README for instructions.

\\ The data contained in this file were retrieved from the NIST CODATA 2022 database.

\\ Eite Tiesinga, Peter J. Mohr, David B. Newell, and Barry N. Taylor (2024), "The 2022 CODATA
\\ Recommended Values of the Fundamental Physical Constants" (Web Version 9.0). Database developed
\\ by J. Baker, M. Douma, and S. Kotochigova. Available at https://physics.nist.gov/constants,
\\ National Institute of Standards and Technology, Gaithersburg, MD 20899.


#import "../common_packages.typ": *

#let angstromStar = (
  val: 1.00001495e-10,
  uncert: 9e-17,
  unit: "m",
  symbol: $AA^*$,
  quantity: "Angstrom star"
)
#let copperXUnit = (
  val: 1.00207697e-13,
  uncert: 2.8e-20,
  unit: "m",
  symbol: $upright(x) u(upright(C) u K alpha_upright(1))$,
  quantity: "Copper x unit"
)
#let latticeParameterOfSilicon = (
  val: 5.431020511e-10,
  uncert: 8.9e-18,
  unit: " m",
  symbol: $a$,
  quantity: "lattice parameter of silicon"
)
#let latticeSpacingOfIdealSi220 = (
  val: 1.920155716e-10,
  uncert: 3.2e-18,
  unit: " m",
  symbol: $d_220$,
  quantity: "lattice spacing of ideal Si (220)"
)
#let molarVolumeOfSilicon = (
  val: 1.205883199e-05,
  uncert: 6e-13,
  unit: "m^3 mol^-1",
  symbol: $V_upright(m) (S i)$,
  quantity: "molar volume of silicon"
)
#let molybdenumXUnit = (
  val: 1.00209952e-13,
  uncert: 5.3e-20,
  unit: "m",
  symbol: $upright(x) u(upright(M) o K alpha_upright(1))$,
  quantity: "Molybdenum x unit"
)
