import textwrap
from typing import Final

# Some constants
# CODATA_BASE_URL: Final = ulibp.urlsplit("https://physics.nist.gov")
CODATA_BASE_URL: Final[str] = "https://physics.nist.gov"
CODATA_CONSTANT_LATEX_IMAGE_BASE_URL = f"{CODATA_BASE_URL}/cuu/Constants/Value/gif/"

AUTOGENERATED_TEXT_CODATA2022: Final[str] = textwrap.dedent(
    """\
    This file was autogenerated. Please refer to the project README for instructions.

    The data contained in this file were retrieved from the NIST CODATA 2022 database.

    Eite Tiesinga, Peter J. Mohr, David B. Newell, and Barry N. Taylor (2024), "The 2022 CODATA
    Recommended Values of the Fundamental Physical Constants" (Web Version 9.0). Database developed
    by J. Baker, M. Douma, and S. Kotochigova. Available at https://physics.nist.gov/constants,
    National Institute of Standards and Technology, Gaithersburg, MD 20899.\n
    """
)
